'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PuertaEntrada
    
    '''<summary>
    '''upPanelMensajes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPanelMensajes As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divErrorPuertaEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErrorPuertaEntrada As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''msgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divSuccessPuertaEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessPuertaEntrada As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''msgSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgSuccess As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFolio As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFechaCita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaCita As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFolioValido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolioValido As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaValida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaValida As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPlacas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacas As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTipoTrasporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoTrasporte As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtNombreTransportista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreTransportista As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLicencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLicencia As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTipoLicencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoLicencia As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOperador As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtHoraLlamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoraLlamado As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTipoPaseEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoPaseEntrada As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnRegistrarDiscrepancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarDiscrepancia As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''lblMostrarArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMostrarArchivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblP_EnableVGM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP_EnableVGM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblP_SolTarjeton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP_SolTarjeton As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gridIngresoUnidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridIngresoUnidades As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnPermitirIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPermitirIngreso As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''upPanelFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPanelFile As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblNombreArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreArchivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ltEmbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltEmbed As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''imageArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imageArchivo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''upModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblModalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''comboTipoDiscrepancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboTipoDiscrepancia As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComentarios As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnEnvDiscrepancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnvDiscrepancia As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''upModalTarjeton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upModalTarjeton As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblModalTitTarjeton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalTitTarjeton As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNoTarjeton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoTarjeton As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnContinuarIngresoT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinuarIngresoT As Global.System.Web.UI.WebControls.LinkButton
End Class
